services:
  auth:
    build: ./auth
    container_name: auth
    image: "ticketing/auth"
    working_dir: /usr/src/app
    command: npm run dev:auth

    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
